version: "3.7"
services:
  app:
    image: 127.0.0.1:5000/rubydoc-app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config:/app/config
      - ./repos:/app/repos
      - ./data:/app/data
      - ./log:/app/log
    ports:
      - "80:8080"
  docparse:
    image: 127.0.0.1:5000/rubydoc-docparse
    build:
      context: ./docker/docparse
    entrypoint: sh -c "echo Docparse image is built. It is okay for this service to exit."
  # cache:
  #   build:
  #     context: .
  #     dockerfile: ./docker/cache/Dockerfile
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - app
