version: "2.4"
services:
  app:
    privileged: true
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./config:/app/config
      - ./repos:/app/repos
      - ./data:/app/data
      - ./log:/app/log
    logging:
      driver: "json-file"
      options:
        max-size: "512k"
        max-file: "3"
    cpu_percent: 80
  cache:
    build:
      context: .
      dockerfile: ./docker/cache/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app
