version: '3.7'
services:
  app:
    privileged: true
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    expose:
      - "8080"
    volumes:
      - ./config:/app/config
      - ./repos:/app/repos
      - ./data:/app/data
      - ./log:/app/log
  cache:
    build:
      context: .
      dockerfile: ./docker/cache/Dockerfile
    expose:
      - "80"
    ports:
      - "3000:80"
    depends_on:
      - app
  https:
    build:
      context: .
      dockerfile: ./docker/https/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - cache
      - app
