version: '3.7'
services:
  app:
    privileged: true
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      args:
        - DOCKER_DEV=1
    volumes:
      - ./config:/app/config
      - ./repos:/app/repos
      - ./data:/app/data
      - ./log:/app/log
    ports:
      - "8080:8080"
  cache:
    build:
      context: .
      dockerfile: ./docker/cache/Dockerfile
    ports:
    - "3000:80"
    depends_on:
      - app
